/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
	interface PlCmBanner {
		apiURL: string;
		bannerType: string;
		contentType: string;
		language: string;
		medium: string;
		trackingId: string;
	}
}
declare global {
	interface HTMLPlCmBannerElement
		extends Components.PlCmBanner,
			HTMLStencilElement {}
	var HTMLPlCmBannerElement: {
		prototype: HTMLPlCmBannerElement;
		new (): HTMLPlCmBannerElement;
	};
	interface HTMLElementTagNameMap {
		"pl-cm-banner": HTMLPlCmBannerElement;
	}
}
declare namespace LocalJSX {
	interface PlCmBanner {
		apiURL?: string;
		bannerType?: string;
		contentType?: string;
		language?: string;
		medium?: string;
		trackingId?: string;
	}
	interface IntrinsicElements {
		"pl-cm-banner": PlCmBanner;
	}
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
	export namespace JSX {
		interface IntrinsicElements {
			"pl-cm-banner": LocalJSX.PlCmBanner &
				JSXBase.HTMLAttributes<HTMLPlCmBannerElement>;
		}
	}
}
